apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-development
  name: nginx-development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-development
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-development
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        ports:
        - containerPort: 80
          protocol: TCP
status: {}
